/**
 * market/providers/secProvider.js — SEC EDGAR Data Provider
 *
 * Responsibility:
 *  Fetches company profile data from the SEC EDGAR public API.
 *  This is the only file in the application that communicates
 *  with SEC EDGAR.
 *
 * What does not belong here:
 *  No Redis, no caching, no business logic, no HTTP handlers.
 *  This file only knows how to call SEC EDGAR and return a clean object.
 *
 * How it fits into the request flow:
 *  market/service.js checks Redis first (profile:TICKER, 24h TTL).
 *  On a cache miss, service.js calls secProvider.getStockProfile(),
 *  stores the result in Redis, then returns it to the controller.
 *  This file is never called directly by a controller.
 *
 * Why SEC EDGAR:
 *  US government public API. No API key. No rate limit concerns.
 *  No licensing restrictions. Free forever.
 *
 * SEC EDGAR endpoints used:
 *  Company submissions (profile data):
 *    https://data.sec.gov/submissions/CIK{cik}.json
 *  CIK is looked up from tickers.json (loaded in memory by tickerSearch.js)
 *
 * CIK format:
 *  SEC requires a 10-digit zero-padded CIK.
 *  Example: Apple Inc. CIK 320193 → '0000320193'
 *  This padding was applied when tickers.json was generated by
 *  transformTickers.js so no conversion is needed here.
 */

const axios = require('axios')
const { searchTickers } = require('../utils/tickerSearch')

// SEC EDGAR requires a User-Agent header on every request.
// Requests without it are rejected with a 403 Forbidden response.
// Format: AppName/Version contact@email.com
// This identifies your application to the SEC in case of issues.
const SEC_USER_AGENT = 'RookieBulls/1.0 dev@rookiebulls.com'

/**
 * getCIK(ticker)
 *
 * Looks up the CIK (Central Index Key) for a ticker symbol.
 * CIK is the SEC's internal identifier for every registered company.
 * It is required to call the SEC EDGAR submissions API.
 *
 * How it works:
 *  Searches tickers.json in memory for an exact ticker match.
 *  tickers.json was downloaded from SEC EDGAR and committed to the repo.
 *  The search is case-insensitive and returns the first exact match.
 *
 * Returns the CIK string (10-digit zero-padded) or null if not found.
 */
const getCIK = (ticker) => {
  // searchTickers() does a partial match — we need an exact ticker match.
  // Filter the results to find the entry where ticker matches exactly.
  const results = searchTickers(ticker)
  const match = results.find(r => r.ticker.toUpperCase() === ticker.toUpperCase())

  if (!match) return null

  // searchTickers() strips CIK from its return shape (it is internal data).
  // We need to reach back into tickers.json directly for the CIK.
  // Require tickers.json here — Node caches it so no extra disk read.
  const tickers = require('../data/tickers.json')
  const entry = tickers.find(t => t.ticker.toUpperCase() === ticker.toUpperCase())

  return entry ? entry.cik : null
}

/**
 * getStockProfile(ticker)
 *
 * Fetches company profile information from SEC EDGAR.
 *
 * Flow:
 *  1. Look up CIK from tickers.json in memory
 *  2. Call SEC EDGAR submissions API with the CIK
 *  3. Extract and return relevant profile fields
 *
 * SEC EDGAR submissions response shape (abbreviated):
 *  {
 *    name: 'Apple Inc.',
 *    tickers: ['AAPL'],
 *    exchanges: ['Nasdaq'],
 *    sic: '3571',
 *    sicDescription: 'Electronic Computers',
 *    description: '...',   ← not always present
 *    ...
 *  }
 *
 * Returns:
 *  { name, ticker, exchange, industry, description, cik }
 *
 * Throws:
 *  404 — ticker not found in tickers.json or CIK lookup fails
 *  503 — SEC EDGAR is unreachable
 */
const getStockProfile = async (ticker) => {
  const normalized = ticker.toUpperCase()

  // Step 1: look up CIK from in-memory tickers.json
  const cik = getCIK(normalized)

  if (!cik) {
    const err = new Error(`Ticker not found in ticker list: ${normalized}`)
    err.statusCode = 404
    throw err
  }

  // Step 2: call SEC EDGAR submissions API
  // URL format: https://data.sec.gov/submissions/CIK{10-digit-cik}.json
  const url = `https://data.sec.gov/submissions/CIK${cik}.json`

  try {
    const response = await axios.get(url, {
      timeout: 8000,
      headers: {
        'User-Agent': SEC_USER_AGENT,
        'Accept': 'application/json',
      },
    })

    const data = response.data

    // Step 3: extract relevant fields
    // sicDescription is the closest field to an industry label in EDGAR data.
    // description is not always present — default to empty string if missing.
    return {
      name:        data.name || normalized,
      ticker:      normalized,
      exchange:    data.exchanges?.[0] || 'N/A',
      industry:    data.sicDescription || 'N/A',
      description: data.description || '',
      cik,
    }

  } catch (err) {
    if (err.statusCode) throw err

    const error = new Error(`SEC EDGAR unreachable for ticker ${normalized}: ${err.message}`)
    error.statusCode = 503
    throw error
  }
}

module.exports = { getStockProfile }