/*
 * FILE: server/modules/auth/model.js
 *
 * RESPONSIBILITY:
 *   Defines the MongoDB schema and Mongoose model for the User collection.
 *   This file describes what a user document looks like in the database.
 *
 * WHAT DOES NOT BELONG HERE:
 *   - Password hashing (that belongs in auth/service.js)
 *   - Token generation (that belongs in auth/service.js)
 *   - HTTP logic (that belongs in auth/controller.js)
 *   - Validation of request input (that belongs in auth/validators.js)
 *
 * HOW IT FITS:
 *   service.js calls this model to create and query user documents.
 *   The model is the only layer allowed to directly touch MongoDB.
 *
 * STEP 7 ADDITIONS:
 *   firstName, lastName         — required on registration
 *   isVerified                  — gate for login access
 *   verificationToken           — random hex token emailed to user
 *   verificationExpiry          — token expires 24h from generation
 *   displayName, country, phone, bio — optional profile fields
 */

const mongoose = require('mongoose');

const userSchema = new mongoose.Schema(
  {
    // ── Identity ─────────────────────────────────────────────────────────────

    email: {
      type: String,
      required: [true, 'Email is required'],
      unique: true,
      lowercase: true,
      trim: true,
    },

    passwordHash: {
      type: String,
      required: [true, 'Password hash is required'],
      /*
       * select: false excludes this field from all query results by default.
       * Must be explicitly requested with .select('+passwordHash').
       * Prevents accidental exposure if a user object is ever serialised.
       */
      select: false,
    },

    role: {
      type: String,
      enum: ['user', 'admin'],
      default: 'user',
    },

    // ── Name (Step 7) ─────────────────────────────────────────────────────────

    firstName: {
      type: String,
      required: [true, 'First name is required'],
      trim: true,
    },

    lastName: {
      type: String,
      required: [true, 'Last name is required'],
      trim: true,
    },

    // ── Email verification (Step 7) ───────────────────────────────────────────

    isVerified: {
      /*
       * Controls whether this user can log in.
       * Set to false on registration.
       * Set to true only after the user clicks the verification link.
       * Login is hard-blocked until this is true.
       */
      type: Boolean,
      default: false,
    },

    verificationToken: {
      /*
       * A 64-character hex string generated by crypto.randomBytes(32).
       * Stored here, emailed to the user as part of the verify link.
       * Nulled out after successful verification — no stale data.
       *
       * sparse: true means the unique index only applies to documents
       * where this field is NOT null. Without sparse, MongoDB would
       * reject multiple verified users all having null here.
       */
      type: String,
      default: null,
      index: { sparse: true },
    },

    verificationExpiry: {
      /*
       * The exact timestamp (milliseconds) when the token becomes invalid.
       * Set to Date.now() + 24 hours at registration and on each resend.
       * Checked server-side: if Date.now() > verificationExpiry → expired.
       */
      type: Date,
      default: null,
    },

    // ── Optional profile fields (Step 7) ─────────────────────────────────────

    displayName: {
      /*
       * A public-facing alias. Useful for leaderboards and community features.
       * Not required — users can skip it.
       */
      type: String,
      trim: true,
      default: null,
    },

    country: {
      /*
       * ISO 3166-1 alpha-2 country code (e.g. 'CA', 'US').
       * Populated from countries.js dropdown on the Profile page.
       * Useful later for TSX (Canadian market) support.
       */
      type: String,
      default: null,
    },

    phone: {
      type: String,
      trim: true,
      default: null,
    },

    bio: {
      /*
       * Short self-description. Capped at 200 characters.
       * Enforced in validators.js — the schema does not limit length
       * because Mongoose maxlength errors are harder to surface cleanly.
       */
      type: String,
      trim: true,
      default: null,
    },
  },
  {
    timestamps: true, // Adds createdAt and updatedAt automatically
  }
);

/*
 * MODEL EXPORT
 *
 * mongoose.model('User', userSchema) registers this schema under 'User'
 * and maps it to the 'users' collection in MongoDB.
 *
 * Imported in service layers to run queries:
 *   User.create()
 *   User.findOne()
 *   User.findById()
 *   User.findByIdAndUpdate()
 */
const User = mongoose.model('User', userSchema);

module.exports = User;